name: Log Opened Issue

on:
  issues:
    types: [opened]

jobs:
  log-issue:
    runs-on: ubuntu-latest

    steps:
      - name: Log GitHub issue
        env:
          ISSUE: ${{ toJSON(github.event.issue) }}
        run: |
          echo "GitHub Issue:"
          echo "$ISSUE"
          
